# Generated by Django 4.0.5 on 2022-06-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_yoga', '0002_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.IntegerField(blank=True),
        ),
    ]
